"""create posts table

Revision ID: bfea073458de
Revises: cc3331795bac
Create Date: 2021-07-08 15:28:25.756555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfea073458de'
down_revision = 'cc3331795bac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'status',
               existing_type=mysql.ENUM('Publish', 'Draft', 'Thrash'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'status',
               existing_type=mysql.ENUM('Publish', 'Draft', 'Thrash'),
               nullable=True)
    # ### end Alembic commands ###
